---
title: "MCMC4Attempt"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
one = c(0, 1, 0, 0, 0, 0, 1)
two = c(1, 0, 1, 0, 0, 1, 0)
three = c(0, 1, 0, 1, 1, 0, 0)
four = c(0, 0, 1, 0, 0, 0, 0)
five = c(0, 0, 1, 0, 0, 0, 0)
six = c(0, 1, 0, 0, 0, 0, 0)
seven = c(1, 0, 0, 0, 0, 0, 0)

distance41 = data.frame(one, two, three, four, five, six, seven)

one1 = c(0, 1, 1, 0, 0, 0, 0)
two1 = c(1, 0, 0, 1, 1, 0, 0)
three1 = c(1, 0, 0, 0, 0, 1, 1)
four1 = c(0, 1, 0, 0, 0, 0, 0)
five1 = c(0, 1, 0, 0, 0, 0, 0)
six1 = c(0, 0, 1, 0, 0, 0, 0)
seven1 = c(0, 0, 1, 0, 0, 0, 0)

distance42 = data.frame(one1, two1, three1, four1, five1, six1, seven1)
```


```{r}
p4 = function(msa, arrangement) {
  
  prob = 1
  
  if(arrangement) {
    
    distance = distance41
    
  } else {
    distance = distance42
  }
  
  for( i in 1:4) {
    
    first = msa[1]
    second = msa[2]
    third = msa[3]
    fourth = msa[4]
    chary1 = as.numeric(substring(first, i, i))
    chary2 = as.numeric(substring(second, i, i))
    chary3 = as.numeric(substring(third, i, i))
    chary4 = as.numeric(substring(fourth, i, i))
    
    intermediate = 0
    
    # x1
    for(j in 0:1) {
      
      # x2
      for(k in 0:1) {
        
        # x3
        for(l in 0:1) {
          
          # p(x1)
          pcurr = 0.5
          
          # p(x2|x1)
          pcurr = pcurr*ifelse(j==k, 1/2+1/2*exp(-2*rate), 1/2-1/2*exp(-2*rate))
          
          
          # p (x3 | x1) or p(x3 | x2) depending on where the adjacency is
          pcurr = pcurr*ifelse(distance[1, 3] == 1, 
                               ifelse(j == l, 1/2+1/2*exp(-2*rate), 
                                      1/2-1/2*exp(-2*rate)), 
                               ifelse(k == l, 1/2+1/2*exp(-2*rate), 
                                      1/2-1/2*exp(-2*rate)))
        
          print(pcurr)
          for(m in 1:3) {
            for(n in 4:7) {
              
              temp = switch(m, 
                            j, k, l)
              
              char = switch(n-3, chary1, chary2, chary3, chary4)
              
              pcurr = pcurr*ifelse(distance[m, n] == 1, 
                                                  ifelse(char == temp, 
                                                    1/2+1/2*exp(-2*rate), 
                                                    1/2 - 1/2*exp(-2*rate)),
                                                1)
            }
          }
        
          intermediate = intermediate + pcurr
          
          
        }
      }
    }
    prob = prob*intermediate
  }
  
  return(prob)
}
```


```{r}
mh4 = function(gamma, initial_point, n_iters) {
  
  placeholder = rep(0, n_iters)
  
  # first, second, third, fourth, arrangement
  
  samples = data.frame(placeholder, placeholder, placeholder, placeholder, placeholder)
  current_point = initial_point
  current_arrangement = 0
  
  for (i in 1:n_iters) {
    
    proposed_arrangement = ifelse(current_arrangement, simulate(Bern(0.6)), simulate(Bern(0.4)))
    proposal = sample(current_point, 4, replace = FALSE)
    
    ratio = gamma(proposal, proposed_arrangement) / gamma(current_point, current_arrangement)
    
    
    if (runif(1) < ratio) {
      
      current_point = proposal
      current_arrangement = proposed_arrangement
      
    }
    
  samples[i, 1] = current_point[1]
  samples[i, 2] = current_point[2]
  samples[i, 3] = current_point[3]
  samples[i, 4] = current_point[4]
  samples[i, 5]= current_arrangement
  
  }
  
  return(samples)
  
}
```

```{r}

msa = c("110", "101", "111", "100")
samples = mh4(p4, msa, 2)

```