---
title: "MCMC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("ggplot2")
```

## MCMC Implementation


```{r}

# adjacency matrix columns

o1 = c(0, 1, 0, 0, 1)
t1 = c(1, 0, 1, 1, 0)
th1 = c(0, 1, 0, 0, 0)
f1 = c(0, 1, 0, 0, 0)
fi1 = c(1, 0, 0, 0, 0)

distance3 = data.frame(o1, t1, th1, f1, fi1)

simulate <- function(distribution) {
  r(distribution)(1) # sample once from the given distribution
}


```


```{r}

p <- function(msa) {
  
  prob = 1
  
  #iterate through each character
  for(i in 1:3) {
    
    first = msa[1]
    second = msa[2]
    third = msa[3]
    chary1 = as.numeric(substring(first, i, i))
    chary2 = as.numeric(substring(second, i, i))
    chary3 = as.numeric(substring(third, i, i))
    
    intermediate = 0
    # sum over x1
    for(j in 0:1) {
      
      # sum over x2
      for(k in 0:1) {
        
        pcurr = 0.5
        pcurr = ifelse(j==k, 1/2+1/2*exp(-2*rate), 1/2-1/2*exp(-2*rate))
        
        
        for(m in 1:2) {
          for(n in 3:5) {
            
            temp = ifelse(m ==1, j, k)
            
            char = switch(n-2, 
                          chary1, 
                          chary2, 
                          chary3)
          
            pcurr = pcurr*ifelse(distance3[m, n] == 1, 
                                                  ifelse(char == temp, 
                                                    1/2+1/2*exp(-2*rate), 
                                                    1/2 - 1/2*exp(-2*rate)),
                                                1)
          }
        }
        
        intermediate = intermediate + pcurr
        
      }
    }

    prob = prob*intermediate
  }
    
  
  return(prob)
  
}
```



```{r}


mh = function(gamma, initial_point, n_iters) {
  
  placeholder = rep(0, n_iters)
  samples = data.frame(placeholder, placeholder, placeholder)
  current_point = initial_point
  
  rate = 0.0001
  
  for (i in 1:n_iters) {
    
    proposal = sample(current_point, 3, replace = FALSE)
    ratio = gamma(proposal) / gamma(current_point)
    
    if (runif(1) < ratio) {
      
      current_point = proposal
      
    }
    
  samples[i, 1] = current_point[1]
  samples[i, 2] = current_point[2]
  samples[i, 3] = current_point[3]
  
  }
  
  return(samples)
  
}


```


```{r}
msa = c("110", "101", "010")

msa1 = c("110", "110", "111")
samples = mh(p, msa, 1000)

organized = samples %>%
  group_by(placeholder.2) %>%
  summarize(n = n())
  
organized

```


```{r}
barplot(height = organized$n/sum(organized$n), names = organized$placeholder.2, ylim = c(0, 0.8), xlab = "Leaf 3", y = "probability")

```



