---
title: "FinalProjectSNIS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(distr))
library(extraDistr)
```

# SNIS Approach

```{r}
 
# columns of the adjacency matrix
o1 = c(0, 1, 0, 0, 1)
t1 = c(1, 0, 1, 1, 0)
th1 = c(0, 1, 0, 0, 0)
f1 = c(0, 1, 0, 0, 0)
fi1 = c(1, 0, 0, 0, 0)

distance = data.frame(o1, t1, th1, f1, fi1)

# columns of the arrangements 
one = c(1, 2, 3)
two = c(1, 3, 2)
three = c(2, 3, 1)
orders = data.frame(one, two, three)


```



```{r}

posterior = function(ppl_function, number_of_iterations) {
  numerator = 0.0
  denominator = 0.0
  for (i in 1:number_of_iterations) {
    weight <<- 1.0
    g_i = ppl_function()
    numerator = numerator + weight * g_i
    denominator = denominator + weight
  }
  return(numerator/denominator)
}

# change p function from original SNIS implementation

p <- function(arrangement, rate, msa) {
  
  
  
  prob = 1
  
  #iterate through each character
  for(i in 1:3) {
    
    first = msa[orders[1, arrangement]]
    second = msa[orders[2, arrangement]]
    third = msa[orders[3, arrangement]]
    chary1 = substring(first, i, i)
    chary2 = substring(second, i, i)
    chary3 = substring(third, i, i)
    
    intermediate = 0
    # sum over x1
    for(j in 0:1) {
      
      # sum over x2
      for(k in 0:1) {
        
        px1 = 0.5
        px2 = ifelse(j==k, 1/2+1/2*exp(-2*rate), 1/2-1/2*exp(-2*rate))
        
        px1y1 = ifelse(distance[1, 3] == 1, 
                       ifelse(chary1 == j, 
                              1/2+1/2*exp(-2*rate), 
                              1/2 - 1/2*exp(-2*rate)),
                       1)
          
        px1y2 = ifelse(distance[1, 4] == 1, 
                       ifelse(chary2 == j, 
                              1/2+1/2*exp(-2*rate), 
                              1/2 - 1/2*exp(-2*rate)),
                       1)
          
        px1y3 = ifelse(distance[1, 5] == 1, 
                       ifelse(chary3 == j, 
                              1/2+1/2*exp(-2*rate), 
                              1/2 - 1/2*exp(-2*rate)),
                       1)
          
        px2y1 = ifelse(distance[2, 3] == 1, 
                       ifelse(chary1 == k, 
                              1/2+1/2*exp(-2*rate), 
                              1/2-1/2*exp(-2*rate)),
                       1)
          
        px2y2 = ifelse(distance[2, 4] == 1, 
                       ifelse(chary2 == k, 
                              1/2+1/2*exp(-2*rate), 
                              1/2-1/2*exp(-2*rate)),
                       1)
          
        px2y3 = ifelse(distance[2, 5] == 1, 
                       ifelse(chary3 == k, 
                              1/2+1/2*exp(-2*rate), 
                              1/2-1/2*exp(-2*rate)),
                       1)
        
        intermediate = intermediate + px1*px2*px1y1*px1y2*px1y3*px2y1*px2y2*px2y3
        
      }
    }
    prob = prob*intermediate
    
  }
    
  
  return(prob)
  
}

Bern = function(probability_to_get_one) {
  DiscreteDistribution(supp = 0:1, prob = 
                         c(1-probability_to_get_one, probability_to_get_one))
}

simulate <- function(distribution) {
  r(distribution)(1) # sample once from the given distribution
}

# Use observe(realization, distribution) for observed random variables
observe = function(arrangement, rate, msa) {
  # `<<-` lets us modify variables that live in the global scope from inside a function
  weight <<- weight * p(arrangement, rate, msa) 
}


```



```{r}
msa = c("110", "101", "010")

tree = function() {
  
  arrangement = as.numeric(rdunif(1, 1, 3))
  rate = 0.0001
  observe(arrangement, rate, msa)
  
  return(arrangement) 
}


```

```{r}
post = posterior_particles(tree, 1000)

sample = post$sample
norm_weights = post$weights/sum(post$weights)
library("ggplot2")
posterior.as.df <- data.frame(slopes = sample[ ,1], norm_weights)
ggplot(posterior.as.df, aes(x = slopes, weight = norm_weights)) + 
  geom_histogram(binwidth = 1) + 
  xlim(0, 4) +
  xlab("Arrangement Number") + 
  ylab("probability") +
  theme_minimal()

```

